### ISSUE TITLE
WRT3200ACM U-boot recovery for New Winbond chip?

### ISSUE THREAD

**Issue by gazaai** [ValCher1961/McDebian_WRT3200ACM#1] opened 2018-01-21 18:05 UTC
Hi, I am unable to recover my WRT3200ACM as the version listed here is for the older style hardware which is:
U-Boot 2013.01 (Apr 08 2016 - 15:47:50) Marvell version: 2015_T1.QA.0p16

Boot version : v0.0.4

The one that came with mine was:
U-Boot 2013.01 (Sep 25 2017 - 11:42:52) Marvell version: 2015_T1.QA.0p16

Boot version : v1.0.0

It gets stuck in a boot loop with the v0.0.4 version.
Can you help me out?

**Comment by ValCher1961** [comment] 2018-01-21 19:56
Hi, @gazaai .
Show your download log.

**Comment by gazaai** [comment] 2018-01-21 20:21
No problem @ValCher1961 

Log is here, I turn off router at end to stop the endless loop:
https://pastebin.com/ufFq5uxR

**Comment by gazaai** [comment] 2018-01-21 21:20
This was it booting properly in the past:
https://pastebin.com/5NvxKJDh

**Comment by ValCher1961** [comment] 2018-01-22 11:02
As I understood correctly, you can not load boot V-0.04, boot V-1.00 is loaded normally?

**Comment by gazaai** [comment] 2018-01-22 11:09
Well yes but 1.0.0 came with the router but I don't have a copy of this so cant put it back on :/

The only one available on the internet is 0.0.4 and I don't know how to compile u-boot so would be happy if you could help me.

Thanks

**Comment by ValCher1961** [comment] 2018-01-22 11:56
Unfortunately I am also not strong in compiling U-boot, because there are a lot of variables.
The only option is to ask the owners of the new versions to make a copy of the section U-Boot V-1.00.
To make it very simple, it is necessary to execute the command - 
`dd if =/dev/mtd0 of =/tmp/mtd0.bin `
on the working router.
The resulting image can be used for recovery.

Another question, is your WRT3200ACM applied NAND-chip Winbond?

**Comment by gazaai** [comment] 2018-01-22 12:00
Perfect, I'll ask another owner then!

Yes my WRT3200ACM was purchased just last week and has the new Winbond NAND chip. Hence the reason I am in this mess lol as I did not know they changed the hardware slightly.

**Comment by ValCher1961** [comment] 2018-01-22 12:05
If you have where to take the image, it will solve your problem.
Please keep me informed of your actions, it will help other users.

**Comment by gazaai** [comment] 2018-01-22 12:09
Another question is it possible to get this image if the user is on the stock Linksys firmware though as you cannot get file access?

Is there a way to copy the file from router to PC via tftpd?

**Comment by ValCher1961** [comment] 2018-01-22 12:18
Under the control of Linksys No, only running Openwrt or MsDebian, and burn the image to USB Flash.

**Comment by gazaai** [comment] 2018-01-22 12:21
But that’s an issue again lol. OpenWRT etc doesn’t boot on this winbond nand yet so it won’t be possible for him to get the file for me then.

**Comment by ValCher1961** [comment] 2018-01-22 12:25
It is necessary to see commands U-boot, it can have a possibility of unloading from memory. I'll take a look.

**Comment by gazaai** [comment] 2018-01-22 12:33
He has full access to u-boot as he is using the serial cable just no access to memory over SSH etc

**Comment by gazaai** [comment] 2018-01-22 13:01
Maybe instead of writing to /tmp he could write to his USB drive is that possible?

**Comment by ValCher1961** [comment] 2018-01-22 13:08
If it has a serial cable connected to the wrt3200, it can temporarily install OpenWrt and make a copy of the partition. And then go back to Linksys.

**Comment by gazaai** [comment] 2018-01-22 13:12
That's what I am trying to say though there is no OpenWRT image for the Winbond version of WRT3200ACM, so he is stuck to the Linksys firmware for now. You can see some discussion here:

http://lists.infradead.org/pipermail/lede-dev/2018-January/010952.html

**Comment by gazaai** [comment] 2018-01-22 14:24
I've told him just to run the command as "dd if =/dev/mtd0" so it just prints out to the screen / log and I should be able to make it into a bin file that way?

**Comment by Chadster766** [comment] 2018-01-22 15:23
I did backup mtd0 and used that with many versions kwboot programs available from other users. I also used you 38x uart kwd files too.

I'm running into kwboot not being about to connect to the WRT (it did once but never again).

**Comment by Chadster766** [comment] 2018-01-22 15:31
@ValCher1961 compiling u-boot for a generic Marvel 38x should be all we need. I don't really want to compiles a u-boot image for upload to a WRT but instead just get the latest u-boot tools like kwboot which get compiled at the same time as u-boot image.

In the paste kwboot and other u-boot tools could be compiled separately but not longer due to heavy interdependencies with the u-boot "make menuconfig" configuration.

**Comment by ValCher1961** [comment] 2018-01-22 16:34
I looked at the source from Linksys on WRT32X_gpl.
There are two versions of U-Boot in the source:
U-Boot-2014.10
U-Boot-2015.10
But the config is not given, i.e. it is necessary to configure. There are a lot of parameters and I don't know them all.

**Comment by ValCher1961** [comment] 2018-01-22 17:17
@gazaai 
Sorry, accidentally crept the gaps in the command, here is the right command-
`dd if=/dev/mtd0 of=/tmp/mtd0.bin`

**Comment by gazaai** [comment] 2018-01-22 19:37
@ValCher1961 
Great thanks!
Do you know what the file size of mtd0.bin should be?

**Comment by gazaai** [comment] 2018-01-22 19:43
Unfortunately dd doesnt seem to be in the linksys version of u-boot?

"MacKlappstuhl3m
I guess we have a problem:

Marvell>> dd
Unknown command ‘dd’ - try ‘help’

There is no dd on Linksys standard software :confused:"

**Comment by ValCher1961** [comment] 2018-01-22 21:10
Yes, this command is only available at Openwrt or Debian.

**Comment by gazaai** [comment] 2018-01-22 21:13
Ok so not possible at the moment then on this version of WRT3200ACM.
I'll return it on the warranty and get a Negear R8000 most likely.
Linksys selling a router claimed as good for 3rd party software but is not, crazy

**Comment by ValCher1961** [comment] 2018-01-22 21:29
We ask at the forum OpenWrt/lede that anyone would make a copy of the image.

**Comment by Chadster766** [comment] 2018-01-23 02:23
@gazaai LEDE OpenWRT has worked on the WRT3200ACM for a long time. Sure mwlwifi had issues but AFAIK that's nothing to do with loading firmware via u-boot. In the article you post the Winbond issue was taken care of in kernel 4.11 release.

**Comment by Chadster766** [comment] 2018-01-23 02:28
The below link is to some valuable information on how to build kwboot and load a back of the u-boot mtd0 partition binary made using "dd" command.

https://github.com/ValCher1961/McDebian_WRT3200ACM/issues/2#issuecomment-359647361

**Comment by Chadster766** [comment] 2018-01-23 03:43
@gazaai try:

Download these two files to your Linux box:
```

wget --user=mcdebian --password=mcdebian123 http://www.protechs-online.com/downloads/McDebian/u-boot-recovery/x64/kwboot
```
Make kwboot an executable:
```
chmod +x ./kwboot
```
Load my WRT3200ACM V1 u-boot backup binary to the WRT memory:
```
./kwboot -t /dev/ttyUSB0 -b u-boot-wrt3200.bin -B 115200 -p
```
After kwboot loads the u-boot image into WRT memory you should get your standard u-boot prompt which you weren't getting before. Start you tftp server with a copy of u-boot-wrt3200.bin for tftp upload to the WRT3200ACM:
```
setenv serverip 192.168.1.2
tftp 2000000 u-boot-wrt3200.bin
nand erase 0 200000
nand write 2000000 0 200000
reset
```
To load firmware run the kwboot command at the same time you power on the router.

**Comment by Chadster766** [comment] 2018-01-23 04:54
@gazaai you will probably have to use the kwboot that has a patch that adds the "-f" option which worked best for my WRT3200ACM testing:
```
wget --user=mcdebian --password=mcdebian123 http://www.protechs-online.com/downloads/McDebian/u-boot-recovery/x64/kwboot-patched
```

**Comment by gazaai** [comment] 2018-01-23 07:38
Thank you Chadster766. Very helpful I’ll have a look tonight after work. Great help, although still not sure about the openwrt working I got someone to load the latest snapshot of LEDE on to there Winbond WRT3200ACM last night and it still didn’t load surely this will have the 4.11 kernel?

**Comment by gazaai** [comment] 2018-01-23 18:24
@Chadster766 Yeah no joy I thought you said this was version 1 you sent me its still 0.0.4 so its just the same as the others?

Log here: https://pastebin.com/5psAxZVC

Got my hopes up there as well lol

**Comment by Chadster766** [comment] 2018-01-23 18:28
Did you try the kwboot process more than once?

**Comment by gazaai** [comment] 2018-01-23 18:30
I'll try it but what's the point? It's just the same version as the rest I don't think v0.0.4 works with the Winbond NAND.

**Comment by Chadster766** [comment] 2018-01-23 18:37
I would say twice is enough with the binary image I provided.

All we need is to get a u-boot image copy of one of mtd0 from a WRT version the same as yours.

**Comment by gazaai** [comment] 2018-01-23 18:41
MacKlappstuhl on lede-project has the same model as mine. Also has serial access, too bad there is no firmware yet that works on it.

**Comment by ValCher1961** [comment] 2018-01-23 18:58
@Chadster766, @gazaai 
Do you know which NAND chip is installed on wrt32x?

**Comment by Chadster766** [comment] 2018-01-23 18:58
@gazaai if @MacKlappstuhl's router is operational and running LEDE OpenWRT he could probably install dd through opkg and get us a backup of the mtd0 u-boot partition.

```
dd if=/dev/mtd0 of=u-boot-wrt3200-v100.bin

**Comment by Chadster766** [comment] 2018-01-23 19:00
@ValCher1961 I don't know but I've already uploaded the mtd0 backup for it.
```
wget --user=mcdebian --password=mcdebian123 http://www.protechs-online.com/downloads/McDebian/u-boot-recovery/u-boot-wrt32x.bin
```

**Comment by Chadster766** [comment] 2018-01-23 19:02
The WRT32x and WRT3200 u-boots are compatible but the default mtdparts would be wrong in the WRT32x u-boot was loaded onto a WRT3200.

**Comment by gazaai** [comment] 2018-01-23 19:03
Yes that was the plan Chadster766 but there is no version of LEDE / OpenWRT that runs on it yet...

@ValCher1961 Not sure, but I tried flashing the WRT32x bootloader a couple of days ago and it reads the NAND as 256Mb successfully unlike the version above but freezes on the line that begins with: MMC:

**Comment by ValCher1961** [comment] 2018-01-23 19:06
Yes, mtdparts different.
The most correct option to restore wrt3200 is to take a copy of mtd0.

**Comment by ValCher1961** [comment] 2018-01-23 19:10
@gazaai 
Here's how, i.e. WRT32X is compatible with chip Winbond.

**Comment by gazaai** [comment] 2018-01-23 19:18
Log of the Winbond WRT3200ACM trying to boot WRT32X Bootloader:

https://pastebin.com/ze2Sdn1P

**Comment by ValCher1961** [comment] 2018-01-23 19:32
I think someone will make a copy with wrt3200 and you restore the router.

**Comment by ghost** [comment] 2018-01-23 20:00
>  operational and running LEDE OpenWRT

The router is operational - but not running LEDE or OpenWRT. AFAIK there is currently no working image available, I tried the snapshot [published today](https://downloads.lede-project.org/snapshots/targets/mvebu/generic/) but no success. It seems like we have to wait for a working image.

**Comment by Chadster766** [comment] 2018-01-23 20:09
I recommend you temporarily install mcdebian firmware and use USB key for the root file system this way you can easily backup your mtd0 u-boot partition

**Comment by ValCher1961** [comment] 2018-01-23 20:44
@MacKlappstuhl 
I can not understand the reason why it is impossible to flash openwrt/Mcdebian.
If you use the U-boot command to load, there should be no obstacles. The only thing that can be the problem is the variables -env. 
They could be compared.

**Comment by gazaai** [comment] 2018-01-23 20:47
@ValCher1961 I had problems loading it as well, so do many others on the forum. I've yet to see one running it with the Winbond chip. Loaded with Linksys GUI with no success, also tried via u-boot same result.

**Comment by ValCher1961** [comment] 2018-01-23 21:04
U-Boot v-1.00 is designed to work with Winbond.
The image can be pre-loaded into memory and then using the standard U-boot routines to flash the required partitions from memory.

**Comment by Chadster766** [comment] 2018-01-23 22:17
@gazaai did you know that's what kwboot does is load the u-boot image into memory and runs it from there? Then you get a 3sec chance to break the boot sequence and then you can run standard u-boot commands but if you reboot or reset it will boot from mtd0 and fail unless you tftp loaded a new u-boot in.

**Comment by gazaai** [comment] 2018-01-23 22:39
@Chadster766 Yeah I know how it all works. The reason my router is bricked is because I did not know they changed the hardware on this WRT3200ACM so when i got it I was wondering why OpenWRT would not boot. I thought I would try to re install the bootloader to see if there was an issue there. Which is where I am now and found out the chip got changed to a Winbond NAND and that was causing the issues all along.

Too late now like you said I'll have to wait on a copy of someones mtd0 of this device

**Comment by ValCher1961** [comment] 2018-01-24 16:57
@MacKlappstuhl 
As I see it is your start log [LEDE](https://pastebin.com/x7801cS4)  . From the log you can see that the kernel located in the section mtd5 loaded normally, and the error was manifested at the initialization stage of the subsystem UBI, to extract rootfs from mtd6. In McDebian, unlike OpenWRT/LEDE, the rootfs located in UBI is not used, and the external disk is used.
I think you have a great chance to successfully install McDebian on wrt3200acm.
You have to experience it.

**Comment by Chadster766** [comment] 2018-01-30 06:45
@gazaai try this u-boot binary for the WRT3200ACM that Linksys engineering provided.

```
wget --user=mcdebian --password=mcdebian123 http://www.protechs-online.com/downloads/McDebian/u-boot-recovery/WRT3200ACM_uboot_1.0.0.bin
```

**Comment by ValCher1961** [comment] 2018-01-30 07:45
Hi @Chadster766!
This is really V1.0.0! How did you find it?
![v1 0 0](https://user-images.githubusercontent.com/17226948/35553837-84295c48-05aa-11e8-9452-e1168769b43c.JPG)

**Comment by gazaai** [comment] 2018-01-30 09:09
Ah nice find @Chadster766  it would have worked as well but unfortunately it's already been returned under warranty and I'm now running a R7800 with LEDE instead 👍

**Comment by Chadster766** [comment] 2018-01-30 15:44
I'm an independent contractor with Belkin\Linksys. They approved my request for these WRT u-boot binary files.

I have them available on my website but I don't have a wiki page with download links yet.

**Comment by ValCher1961** [comment] 2018-01-30 16:19
@Chadster766, you place the wiki on your page, because my English...  :smile: 
We all do one thing.

**Comment by Chadster766** [comment] 2018-01-30 16:23
Thanks

**Comment by andyVSR** [comment] 2018-02-04 18:17
About uboot-v100-wrt3200.bin and  uboot-v209-wrt32.bin files. Can these be used with WRT3200ACM with NAND AMD/Spansion (S34ML02G2) ?
 I saw some posts on ddwrt saying that they flashed (with no problems) u-boot v209 on wrt3200acm first model (the one with nand amd/spansion).
 When i will have time , i will try to boot these versions using serilal and kwboot (without flashing) to see if its working. but now i am too lazy (or drunk ?) :)

Thanks

**Comment by Chadster766** [comment] 2018-02-04 18:22
For the all WRT3200ACM hardware only use the Linksys provided u-boot recovery binary in link below:

```
wget --user=mcdebian --password=mcdebian123 http://www.protechs-online.com/downloads/McDebian/u-boot-recovery/WRT3200ACM_uboot_1.0.0.bin
```

**Comment by ValCher1961** [comment] 2018-02-04 23:25
I tried to use on WRT3200ACM uboot-v209-wrt32.bin, my router hovered dead at boot. I had to parse the router and close the address bus legs while initializing the code reading from NAND, thus forcing the router to enter the emergency boot mode.
I'm not suggesting you do that.

**Comment by andyVSR** [comment] 2018-02-05 10:49
@ValCher1961 : thanks for the info. acording to this https://www.dd-wrt.com/phpBB2/viewtopic.php?t=311206&postdays=0&postorder=asc&start=60, I thought it is possible. did you tested uboot-v100-wrt3200.bin on the nand amd/spansion too ?

 @Chadster766 : since you are a Linksys conctractor, did you asked them about a solution for open source projects regarding new nand ? there are a lot of people crying on forums about this. can http://downloads.linksys.com/downloads/gpl/WRT32X_gpl_v1.0.170828.208.tar.gz be used for this ?

**Comment by ValCher1961** [comment] 2018-02-05 11:15
@andyVSR 
No, I have not installed uboot-v100-wrt3200.bin on my router, I think the effect would be the same as from uboot-v209-wrt32.bin.

**Comment by Chadster766** [comment] 2018-02-05 14:22
@andyVSR do you have any links to the forums where they are having the nand issue you mention?

**Comment by ghost** [comment] 2018-02-05 14:34
@Chadster766 These are the threads I know about:
https://forum.lede-project.org/t/wrt3200acm-unable-to-flash-lede-successfully/10096
https://forum.lede-project.org/t/wrt3200acm-wont-accept-firmware/10814

**Comment by andyVSR** [comment] 2018-02-05 14:52
@Chadster766 :
https://www.dd-wrt.com/phpBB2/viewtopic.php?t=313051
https://www.dd-wrt.com/phpBB2/viewtopic.php?t=313652
an of course : http://community.linksys.com/t5/Wireless-Routers/WRT3200ACM-and-WRT32X-Firmware-update-available-1-11-2018/td-p/1260723/page/14
where you responded, but  from his logs the kernel loaded ok and then it can not mount rootfs nor make any partion available and i think new nand driver (or other kernel configs) must be included in kernel. the talk there was about flashing a previous wrt3200acm firmware but make sense since it was released before new nand been inroduced. the later releases work on both nand types.

**Comment by ValCher1961** [comment] 2018-02-05 15:07
@andyVSR 
Oh, good idea, if the kernel as seen is loaded without problems, then the driver of the new chip can be included in the kernel!
By the way, our kernel assemblies do not use UBI, i.e. you can install Mcdebian without problems.

**Comment by andyVSR** [comment] 2018-02-05 15:14
@ValCher1961 : i know, you are using external usb.  it is not my case since i have it from 2016 (its old nand). But Mcdebian is for experienced users,  most users want a web gui to make all for them :) .

**Comment by ValCher1961** [comment] 2018-02-05 15:53
@andyVSR 
Yes, I understand you... but so many opportunities you will have from Debian :)

**Comment by ValCher1961** [comment] 2018-02-05 16:07
I think I may be mistaken when you build a kernel image in OpenWrt/Lede, you need to use this flash selection point.
CONFIG_MTD_CFI_STAA=y
![0020](https://user-images.githubusercontent.com/17226948/35814663-85755eba-0a8e-11e8-84b1-a5541f29e6c4.PNG)

**Comment by Chadster766** [comment] 2018-02-05 16:16
Let me know if anyone needs the WRT32X u-boot recovery image. The nand issue mentioned should be easily fixed with a nand driver addition. @ValCher1961 is usually right so I'm guessing adding CONFIG_MTD_CFI_STAA will probably resolve the issue.

**Comment by ghoffman9** [comment] 2018-02-05 18:50
great thread.
i'v got a wrt3200acm that i cross-flashed to wrt32x, and changed to the wrt32x u-boot209.
now i want to go back, but mtd0 is locked.
are there ways to modify the mtd status form the uboot console, prioir to booting into lede or dd-wrt?

**Comment by ValCher1961** [comment] 2018-02-05 19:06
@ghoffman9 
You can go back from uboot by downloading your stock-uboot See 8 item.
```
	setenv ipaddr 192.168.1.1; setenv serverip 192.168.1.99
	nand device 0
	tftp 8000000 uboot-vXXX-wrtNNNN.bin
	nand erase.spread 0 200000
	nand write 8000000 0 f4000
	resetenv
```

**Comment by ValCher1961** [comment] 2018-02-05 21:11
`CONFIG_MTD_CFI_STAA=y` 
The default is included in  `/arch/arm/configs/mwebu_v7_defconfig`, but I don't know if it's included in OpenWrt/Lede.

**Comment by ghoffman9** [comment] 2018-02-06 13:14
@ValCher1961 -
thnak you - worked perfectly. however my boot sequence is now not present on the serial port.
what steps are necessary to get boot logging to serial port back on?

**Comment by ValCher1961** [comment] 2018-02-06 15:39
@ghoffman9, I correctly understood you, you loaded into mtd0 uboot from wrt32x and now your wrt3200 is frozen?

**Comment by ghoffman9** [comment] 2018-02-06 15:57
@ValCher1961 - it's weird.
after successfully burnng uboot 1.0 form macdebian site using the tftp/nand.. commands that you detailed, i issued resetenv, then reset, in attmep to get defualt uboot environment vars. after 'reset', it looked like the console froze at that time. then no console output on reboot, with or without attempts to interrupt.
after about 5 power cycles, i get a console output again. i've interrupted it, but i'm not at therouter again till tonight. i'm afraid to recycle power until i get  ahandle on what's goin on.
i know the uboot209 (wrt32x) has silent=1 embedded in it, but the uboot0.4 and uboot1.0 do not. therefore i was trying to reset uboot environment to get rid of that setting.
now it seems like the router is in an unstable boot state

**Comment by Chadster766** [comment] 2018-02-06 16:04
Have you done a "resetenv" to set the envars to the defaults for the u-boot version?

**Comment by ghoffman9** [comment] 2018-02-06 16:24
yes, i did resetenv just after burning the new uboot, then reset (but without saveenv). maybe that was the problem?

**Comment by Chadster766** [comment] 2018-02-06 16:30
I thought resetenv was enough but maybe a save is required.

**Comment by ValCher1961** [comment] 2018-02-06 16:56
I was in this situation when I loaded my wrt3200 uboot from Wrt32.
There is a method of how to get out of this situation, but it is very dangerous!!!
As I wrote earlier, I had to open the router and remove the radiator to get to NAND. Next, close a pair of address pins chip-NAND jumper, turn on the router, through ~ 0.5... 1.0 sec. remove the jumper from the NAND. This action will result in the error of reading the Uboot from NAND at the start and the router goes into the emergency boot mode from the serial port. Next, you can use Kwboot to download a new uboot.

**Comment by Chadster766** [comment] 2018-02-06 17:00
@ValCher1961 interesting, do you have a pic of the jumper?

**Comment by ValCher1961** [comment] 2018-02-06 17:02
The jumper is the tip of the ballpoint pen.

**Comment by Chadster766** [comment] 2018-02-06 17:07
How about a pic of the nand and the pins to jumper?

**Comment by ghoffman9** [comment] 2018-02-06 17:09
i had uboot209 on and it basically worked. on the uboot1.0, i don't think the problem is failure of uboot to load, but the fialure of uboot to report to the console. since i am now at the uboot console on the serial port, the router must have loaded u-boot. what is strange is that there is no silent=1 in the environment now, but there must be with the other reboots that never got to console. 
unless there are other variables  that uboot checks, or other steps in the boot process before the serial console is activated.

**Comment by ValCher1961** [comment] 2018-02-06 17:09
it is possible and so to make

**Comment by ValCher1961** [comment] 2018-02-06 17:13
@ghoffman9, Show your output from the console.

**Comment by Chadster766** [comment] 2018-02-06 17:20
Some USB to TTL cables have to be physically disconnected and reconnected because they don't reconnect on a u-boot reset command.

**Comment by ghoffman9** [comment] 2018-02-06 17:30
[bootlog.uboot10.txt](https://github.com/ValCher1961/McDebian_WRT3200ACM/files/1700104/bootlog.uboot10.txt)
bootlog is attached. shows boot into uboot0.4, then flashing uboot1.0, then reboot. what you dont see is multiple power cycles before a reboot is visible.

thanks!

**Comment by ValCher1961** [comment] 2018-02-06 18:12
@ghoffman9, Your uboot-stock v004?

**Comment by ghoffman9** [comment] 2018-02-06 21:46
the first boot was stock v004. then you see the log of flashing the v1.0 uboot. , then resetenv, then reset, at that point the serial console got nothing for about 5 power cycles. then the log shows uboot1.0, which i interrupted. 
so my router is at home, hopefully still with interrupted uboot on the serial console. i'm tryin gto figure out what's happening in the invisible power cycles.

**Comment by gazaai** [comment] 2018-02-06 22:11
@ghoffman9 Why are you trying to run the v1.0.0 bootloader when your router is supposed to use v0.0.4

**Comment by Chadster766** [comment] 2018-02-06 22:14
@ghoffman9 are you using the official Linksys u-boot binary I provided "WRT3200ACM_uboot_1.0.0.bin" from my previous post?

https://github.com/ValCher1961/McDebian_WRT3200ACM/issues/1#issuecomment-361492842

**Comment by ghoffman9** [comment] 2018-02-06 23:09
@gazaai - good question. i am curious to know what has changed.
@Chadster766 - yes, i am using the official v1.0.0 binary that you provided.

**Comment by ghoffman9** [comment] 2018-02-07 14:33
@ValCher1961, @Chadster766 -
thank you for all your suggestions and help.
it seems that my serial adapter (taio) is holding sonething up in the boot process. if i repower my router wihtt he taoi adapter up and running, i have to 'jiggle' the connections to get he unit to boot. if the serial adapter is disconnected, the router boots normally.

this occurs with uboot v0.0.4 and uboot v1.0.0. does the u-boot look for an image on the serial port all the time, or only in response to some signal?

**Comment by Chadster766** [comment] 2018-02-07 15:28
@ghoffman9 do you have the +5v connected? If so that could explain boot issue with the cable connected.

In one of my previous post I mention that some USB to TTL cables need to disconnected and reconnect at boot time to get connected.

**Comment by gazaai** [comment] 2018-02-07 15:32
@ghoffman9 I think that's really common I have to do this every time. Just boot it with it plugged in but quirky disconnect the ground wire and plug it back in. Then it will boot as normal

**Comment by Chadster766** [comment] 2018-02-07 15:35
The Adafruit USB to TTL doesn't have this issue:
https://www.adafruit.com/product/954

**Comment by ghoffman9** [comment] 2018-02-07 17:51
no 5v wire connected.  i've ordered the adafruit cp2102 adapter.  i'll report back. thanks again,

**Comment by Chadster766** [comment] 2018-02-07 18:11
For the WRT3200 and WRT32x if you don't have a jumper cable I recommend the below:
https://www.amazon.com/2-54mm-2-0mm-pitch-Header-Adapter/dp/B00HFZK652/ref=redir_mobile_desktop?_encoding=UTF8&psc=1&ref_=yo_ii_img

**Comment by jbsky** [comment] 2018-02-07 21:00
@ghoffman9 You have a bad check CRC.

$filesize is undefined when you print your environment variables.

==> update_both_images=tftpboot $defaultLoadAddr $firmwareName && nand erase $priKernAddr $priFwSize && nand erase $altKernAddr $altFwSize && nand write $defaultLoadAddr $priKernAddr $filesize && nand write $defaultLoadAddr $altKernAddr $filesize<==


try ==> setenv filesize 0x0600000
or ==> setenv filesize 0x5000000

Good luck!

**Comment by ValCher1961** [comment] 2018-02-07 22:18
@ghoffman9
What is noticed in the output of your env, you do not have:
```
fileaddr=1000000
filesize=21E0000
partition=nand0,0
mtddevnum=0
mtddevname=uboot
```

**Comment by ghoffman9** [comment] 2018-02-07 22:30
@jbsky , @ValCher1961 -
i think i screwed up my environment by issuing the 'resetenv' command, which loads the environment vars from uboot but must also delete the other ones.

i think i can reconstruct from logs from a few months ago.
i appreciate the continued help.

**Comment by Chadster766** [comment] 2018-02-07 22:33
@ghoffman9 which u-boot binary did you resetenv with? (official or other)

**Comment by ValCher1961** [comment] 2018-02-07 22:45
I saved my ENV right after I bought my router, now I don't have these variables, so my post above can be considered a mistake,  except:
```
fileaddr=1000000
filesize=21E0000
```

**Comment by ghoffman9** [comment] 2018-02-07 22:56
after i burned uboot v1.0.0, i resetenv.
then i went back to v0.0.4 and resetenv again. 
with either version, the boot process is a little flaky.

**Comment by ghoffman9** [comment] 2018-02-08 14:30
i've obtained a cp2102 usb serial adapter and most of the communication problems are gone.
still trying to reconstruct all my environment variables.
stock firmware hangs with a spinning 'waiting' on the login page. logs indicate invalide uuid for the router, even though the variable is there in devinfo. i recall form other linksys discussions that this means some invalid relationship of uuid, wps key, and region. i *hope* i have all my original dumps.
love linksys.

**Comment by ValCher1961** [comment] 2018-02-08 19:33
@ghoffman9 
You made a copy of mtd3, looks like you've ruined this section.

**Comment by ghoffman9** [comment] 2018-02-08 19:58
@ValCher1961 - yes, i did make a copy of mtd3, and mtd4. why does making a copy mean i have ruined this section?

**Comment by ValCher1961** [comment] 2018-02-08 20:42
I have the same stock firmware freeze on the login page.
Look - [](https://community.linksys.com/t5/Wireless-Routers/How-to-restore-the-data-device-ID/td-p/958652)

**Comment by ValCher1961** [comment] 2018-02-08 20:46
I have the same stock firmware freeze on the login page.
[See](https://community.linksys.com/t5/Wireless-Routers/How-to-restore-the-data-device-ID/td-p/958652)

**Comment by ghoffman9** [comment] 2018-02-08 20:54
ok thanks. i'll give it another try tonight, although i have restored all these in devinfo i thought.

**Comment by Chadster766** [comment] 2018-02-08 21:16
The devinfo mtd partition can be rebuilt with information labeled on the WRT32xxxx.

I can get you a copy of the mtd and you can change the devinfo information from OpenWRT or McDebian via fw_printenv\fw_saveenv

**Comment by ghoffman9** [comment] 2018-02-08 21:52
@Chadster766 - that would be great. but can't I edit the devinfo area from uboot and a serial terminal?  doesn't devinfo commit save this to mtd3?

**Comment by Chadster766** [comment] 2018-02-08 21:59
Not that I know of.

I think you can change the fw_config file to point to the devinfo mtd allowing you to edit it easily. I will do some investigation in the settings to change for this. After you update the devinfo partition from open source you can load the Linksys firmware.

**Comment by ValCher1961** [comment] 2018-02-08 22:54
The content of the section looks like this, just insert your values.
```
admin1_passphrase=XXXXXXXXXX
admin2_passphrase=XXXXXXXXXX
cert_region=US
default_passphrase=XXXXXXXXXX
default_ssid=LinksysXXXXX
deviceType=urn:home-linksys-com:device:Router:1
devinfo_version=20160121.1
hw_mac_addr=60:38:E0:XX:XX:XX
hw_revision=1
hw_version=48SAM203.SGD
manufacturer=Linksys, LLC
manufacturerURL=http://www.linksys.com
manufacturer_date=2016/09/26
mfg_data_version=1
modelDescription=Simultaneous Dual-Band Wireless-AC Gigabit Router
modelNumber=WRT3200ACM
serial_number=XXXXXXXXXXXXXX
sw_version=v0.0.4
tc_passphrase=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
tc_ssid=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
uuid_key=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
wps_device_pin=XXXXXXXX
```

**Comment by Chadster766** [comment] 2018-02-08 23:08
Do you have the /etc/fw_env.config settings so he can edit that partition rather than do the old school echo to file?

**Comment by ghoffman9** [comment] 2018-02-09 02:36
@Chadster766 -
'devinfo show' from uboot shows all my settings, checked against your list above.

i loaded both openwrt (your version) and dd-wrt from update_both_images.
when i cat /dev/mtd3>devinfo.bin, i see an unexpected 0A just after the '=' of hw_version. so i thought the devinfo partition might be being misread.
however -
mtd3 is not writeable in either lede or dd-wrt.
also - /etc/fw_env.config does not exist in either firmware.

thoughts?

**Comment by Chadster766** [comment] 2018-02-09 03:09
I think for OpenWRT you have to install uboot-envtools package

**Comment by Chadster766** [comment] 2018-02-09 03:15
The OpenWRT uboot-envtools package has the ability to unlock the partition its working with upon fw_saveenv

**Comment by ghoffman9** [comment] 2018-02-09 13:36
@Chadster766 , @ValCher1961 -
from the uboot conole, this is whati did to get stock working again:

i added two variables to the environment that i noticed in the log of my initial boot of the router:
setenv fileaddr=2000000
setenv filesize=2740100

i cleaned up the devinfo data from the uboot console, using devinfo unset/set/commit sequence. (i think the hw_version string was messed up)

then i ran  update_both_images to tftp the stock firmware, i could log into that now, and then issued a factory reset from stock.  this seems to have restored everything.

by the way - i have done this using the v1.0.0 uboot. looking at the logs, it adds a usb3 driver. 
thank you all for your help. i hope this information helps someone else.

**Comment by Chadster766** [comment] 2018-02-09 14:22
@ghoffman9 Thanks for the information this will come in handy plus I learned something new 😃

**Comment by ValCher1961** [comment] 2018-02-13 20:29
The first time I tried to download uboot-v209-wrt32x. bin to my wrt3200acm/v004 it hung and did not work. Then I managed to revive it only blocking read NAND at boot time. Now I decided to repeat my experiment with loading a new uboot, because I wanted to check whether Uboot-v100 can work with NAND AMD/Spansion. Now I have downloaded uboot-v100-wrt3200. bin, and for the convincing still installed stock-firmware from Linksys and Mcdebian, checked-everything works well as with Uboot-v004. It seems to me that my failure in the first attempt was caused by a data transfer error.



Next i installed uboot-v209-wrt32. bin and downloaded the stock-firmware wrt32x. Uboot normally started the system, but when the kernel was deployed, it failed
```
auto_recovery_check changes bootcmd: run nandboot
Hit any key to stop autoboot:  0

NAND read: device 0 offset 0xa00000, size 0x600000
 6291456 bytes read: OK
Wrong Image Format for bootm command
ERROR: can't get kernel image!
Venom>>

```
And yet, Uboot-v209 works well with stock-firmware WRT3200ACM and Mcdebian.

While it is possible to conclude that  WRT3200ACM [AMD/Spansion] is compatible with Uboot-v100 and Uboot-v209. Compatibility wrt3200acm [Winbond/mxic] with uboot-v004 someone has to check again. For me, it remains a mystery of the format of wrt32x.

How I did it.
```
setenv ipaddr 192.168.1.1; setenv serverip 192.168.1.100
tftp 0x8000000 uboot-v209-wrt32.bin
tftp 0x7000000 mtd3.bin
nand device 0
nand scrub.chip
nand erase.chip
nand write 8000000 0 f4000
nand write 7000000 7e0000 40000
resetenv
setenv ipaddr 192.168.1.1; setenv serverip 192.168.1.100
setenv firmwareName FW_WRT3200ACM_1.0.6.186168_prod.img; run flash_alt_image; run flash_pri_image

```

**Comment by Chadster766** [comment] 2018-02-13 20:47
Users with WRT3200ACMs' that have the Winbond W29N02GV nand flash will not be able to load any open source firmware (including McDebian) because a custom kernel nand driver is required.

Linksys engineering is aware of this Winbond nand issue and hopefully will release a patch to the open source community soon

**Comment by ValCher1961** [comment] 2018-02-13 20:59
So wrt3200 with Winbond can not use Uboot-v004?

**Comment by Chadster766** [comment] 2018-02-13 21:06
The official Linksys u-boot binary I posted works with all nand used in the WRT3200ACM. Its the kernel that doesn't work because those different nands require custom kernel drivers and possibly DTS file changes too.

**Comment by lantis1008** [comment] 2018-02-14 09:09
Surely they must have seen that issue coming?
I look forward to the patches however. Will be nice to produce a bootable image.

**Comment by ValCher1961** [comment] 2018-02-18 20:06
Presented a solution to the problem, [see](https://forum.openwrt.org/viewtopic.php?pid=372284#p372284)

**Comment by Chadster766** [comment] 2018-02-18 20:32
Yes I saw that. I can't test it though since I don't have a WRT with that nand.

**Comment by lantis1008** [comment] 2018-02-18 20:49
Are you doing any work with the WRT32X @chadster766

**Comment by Chadster766** [comment] 2018-02-18 21:12
I have successfully loaded McDebian onto the WRT32x and reverted it back to Linksys stock firmware but I don't plan to officially support it until Linksys has published a u-boot loadable firmware.

**Comment by lantis1008** [comment] 2018-02-18 21:19
Any inside information on delays with this?

**Comment by Chadster766** [comment] 2018-02-18 22:50
Sorry Linksys engineering never provides ETA regarding this type of development.

**Comment by andyVSR** [comment] 2018-02-20 13:39
Hi all,
 as @ValCher1961 said, seems that adding to dts this two lines :
   nand-ecc-strength = <4>;
   nand-ecc-step-size = <512>;
 ,resolves the Winbond nand issues.
 i saw people reporting that is working https://www.dd-wrt.com/phpBB2/viewtopic.php?t=313921&sid=7363784b2e1959631cbc8681d11bcec4

**Comment by ValCher1961** [comment] 2018-02-20 15:49
I have no wrt3200 with Winbond, but I have read the reviews already who have this modification and they also reported that it works.
This patch does not affect the operation of NAND-AMD/Spansion, i.e. the corrected DTS file for both versions of wrt3200.

**Comment by Chadster766** [comment] 2018-02-20 15:54
@ValCher1961 so this patch can be used for all WRTxxxx models with having separate firmwares for nand types? If so that would be great.

**Comment by ValCher1961** [comment] 2018-02-20 16:49
@Chadster766 
Yes, I now have a working kernel with the updated DTS for wrt3200, everything works.
It is desirable that someone else checked it on OPENWRT/Lede, as we in Mcdebian actively do not use NAND.

**Comment by Chadster766** [comment] 2018-02-20 17:26
@ValCher1961 yes but McDebian does need to read nand.

I'm sure LEDE is already aware of the patch :smile:

**Comment by ValCher1961** [comment] 2018-02-20 18:42
@Chadster766 
I checked NAND for read-write to McDebian, I've got everything OK.

**Closed as completed** 2018-03-04 08:29 UTC
